
'use client';

export type AppNotification = {
    id: number;
    type: 'new_user' | 'deposit_request' | 'withdrawal_request' | 'deposit_received' | 'withdrawal_approved';
    message: string;
    timestamp: string;
    status: 'read' | 'unread';
    userId: 'admin' | string; // 'admin' for admin notifications, or a specific user ID
};

// Start with empty notifications, they will be generated by user actions.
export const defaultNotifications: AppNotification[] = [];

    