import { beforeAll, afterAll, describe, expect, it, vi } from 'vitest';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { NextRequest } from 'next/server';
const enabled = process.env.RUN_PROFILE_RULES_EMULATOR === '1' && process.env.FIRESTORE_EMULATOR_HOST === '127.0.0.1:9081';
const handles = vi.hoisted(() => ({ db: null as any, uid: 'engine_owner' }));
vi.mock('@/firebase/admin-init', () => ({ get adminDb() { return handles.db; } }));
vi.mock('@/lib/server-auth', () => ({ verifyRequester: async () => ({ uid: handles.uid }), RequestAuthError: class extends Error {} }));
import { POST as mock } from '@/app/api/mock-test/route';
import { POST as quiz } from '@/app/api/quiz-clash/route';
import { GET as previewSettlement, POST as settle } from '@/app/api/admin/payments/quiz-clash/route';
describe.skipIf(!enabled)('isolated authoritative test transactions', () => {
  let app: ReturnType<typeof initializeApp>, db: ReturnType<typeof getFirestore>;
  const question = { id: 'q1', text: { en: 'Q', mr: 'प्र' }, options: { en: ['A', 'B', 'C', 'D'], mr: ['अ', 'ब', 'क', 'ड'] }, correctAnswer: { en: 'B', mr: 'ब' } };
  const call = (route: (request: NextRequest) => Promise<Response>, body: any) => route(new NextRequest('http://localhost/api/mock-test', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }));
  beforeAll(async () => {
    app = initializeApp({ projectId: 'demo-vidya-profile-rules' }, 'engine-tests'); db = getFirestore(app); handles.db = db;
    await db.doc('users/engine_owner').set({ status: 'Active' });
    await db.doc('users/engine_other').set({ status: 'Active' });
    await db.doc('students/engine_student').set({ parentId: 'engine_owner', name: 'Engine student', academic: { board: 'SSC', standard: '10' }, stats: { testsTaken: 0, avgScore: 0 } });
    await db.doc('testSets/engine_set').set({ board: 'SSC', standard: '10', subject: 'Maths', questions: [question, { ...question, id: 'q2' }, { ...question, id: 'q3' }] });
    await db.doc('transactions/engine_order').set({ user: 'engine_owner', type: 'Purchase', status: 'Completed', amount: -100, finalPrice: 100 });
    await db.doc('studentEntitlements/engine_student').set({ parentId: 'engine_owner', status: 'ACTIVE', accessType: 'PAID_SUBSCRIPTION', productId: 'annual', purchaseTransactionId: 'engine_order', startsAt: '2020-01-01', expiresAt: '2099-01-01' });
    const schedule = { testSetId: 'engine_set', testSetName: 'Engine set', board: 'SSC', standard: '10', subject: 'Maths', dateTime: new Date(Date.now() - 10000).toISOString(), duration: 30 };
    await db.doc('scheduledTests/engine_live').set(schedule);
    await db.doc('scheduledTests/engine_expire').set(schedule);
    await db.doc('quizClashTournaments/engine_quiz').set({ title: 'Engine quiz', type: 'Pro', startTime: new Date(Date.now() - 10000).toISOString(), status: 'live', entryFee: 10, prizePool: 0, registeredUsers: [], questionCount: 2, testSetId: 'engine_set' });
    await db.doc('wallets/engine_owner').set({ balance: 100, reservedBalance: 50 });
  }, 20000);
  afterAll(async () => { await db.terminate(); await deleteApp(app); });
  it('resumes one attempt, protects private answers, serializes saves and submits once under concurrency', async () => {
    const base = { studentId: 'engine_student', testId: 'engine_live' };
    const [start, retry] = await Promise.all([call(mock, { ...base, action: 'start' }), call(mock, { ...base, action: 'start' })]);
    expect(start.status).toBe(200); const first = await start.json(); expect((await retry.json()).attemptId).toBe(first.attemptId);
    expect(first.questions[0]).not.toHaveProperty('correctAnswer');
    expect(first.deadline - first.serverNow).toBeLessThan(1800000);
    const [saveA, saveB] = await Promise.all([call(mock, { ...base, action: 'save', revision: 0, answers: { q1: 1 } }), call(mock, { ...base, action: 'save', revision: 0, answers: { q1: 0 } })]);
    expect([saveA.status, saveB.status].sort()).toEqual([200, 409]);
    const answer = saveA.status === 200 ? 1 : 0;
    const [submitA, submitB] = await Promise.all([call(mock, { ...base, action: 'submit', revision: 1, answers: { q1: answer }, score: 100 }), call(mock, { ...base, action: 'submit', revision: 1, answers: { q1: answer }, score: 100 })]);
    expect(submitA.status).toBe(200); expect(submitB.status).toBe(200);
    expect((await submitA.json()).result.rawScore).toBe(answer === 1 ? 1 : 0);
    expect((await db.doc('students/engine_student').get()).data()?.stats.testsTaken).toBe(1);
    expect((await call(mock, { ...base, action: 'review' })).status).toBe(409);
    handles.uid = 'engine_other'; expect((await call(mock, { ...base, action: 'start' })).status).toBe(403); handles.uid = 'engine_owner';
  }, 30000);
  it('ignores late answer changes, records only autosaved answers and never ranks an expired submission', async () => {
    const base = { studentId: 'engine_student', testId: 'engine_expire' };
    const first = await (await call(mock, { ...base, action: 'start' })).json();
    expect((await call(mock, { ...base, action: 'save', revision: 0, answers: { q1: 0 } })).status).toBe(200);
    await db.doc(`mockTestAttempts/${first.attemptId}`).update({ deadline: Date.now() - 1 });
    expect((await call(mock, { ...base, action: 'save', revision: 1, answers: { q1: 1 } })).status).toBe(409);
    const result = await (await call(mock, { ...base, action: 'submit', revision: 1, answers: { q1: 1 } })).json();
    expect(result.result).toMatchObject({ rawScore: 0, rankingEligible: false, perTestCashPrizeEligible: false });
  }, 30000);
  it('charges a Pro enrollment once, preserves reserved funds and accepts only server-checked quiz progression', async () => {
    const base = { studentId: 'engine_student', tournamentId: 'engine_quiz' };
    const joined = await Promise.all([call(quiz, { ...base, action: 'join' }), call(quiz, { ...base, action: 'join' })]); expect(joined.map(r => r.status)).toEqual([200, 200]);
    expect((await db.doc('wallets/engine_owner').get()).data()).toMatchObject({ balance: 90, reservedBalance: 50 });
    const start = await (await call(quiz, { ...base, action: 'start' })).json(); expect(start.question).not.toHaveProperty('correctAnswer');
    const next = await (await call(quiz, { ...base, action: 'answer', revision: 0, questionId: 'q1', optionIndex: 1, score: 1000 })).json();
    expect(next).toMatchObject({ score: 1, revision: 1, status: 'ACTIVE' });
    expect((await call(quiz, { ...base, action: 'answer', revision: 0, questionId: 'q1', optionIndex: 1 })).status).toBe(409);
    const finished = await (await call(quiz, { ...base, action: 'answer', revision: 1, questionId: 'q2', optionIndex: 1 })).json(); expect(finished).toMatchObject({ score: 2, status: 'FINISHED' });
    const again = await (await call(quiz, { ...base, action: 'quit', revision: 1, questionId: 'q2' })).json(); expect(again.score).toBe(2);
    expect((await db.collection('quizClashResults').where('tournamentId', '==', 'engine_quiz').get()).size).toBe(1);
    const previewResponse = await previewSettlement(new NextRequest('http://localhost/api/admin/payments/quiz-clash?tournamentId=engine_quiz'));
    expect(previewResponse.status).toBe(200);
    const preview = await previewResponse.json();
    expect(preview.rows[0]).toMatchObject({ rank: 1, prize: 3.2, paid: true });
    const approvals = await Promise.all([call(settle, { tournamentId: 'engine_quiz', action: 'close-and-settle', previewHash: preview.previewHash }), call(settle, { tournamentId: 'engine_quiz', action: 'close-and-settle', previewHash: preview.previewHash })]);
    expect(approvals.map(r => r.status)).toEqual([200, 200]);
    expect((await db.doc('wallets/engine_owner').get()).data()).toMatchObject({ balance: 93.2, reservedBalance: 50 });
    expect((await db.collection('transactions').where('type', '==', 'Prize').get()).size).toBe(1);
  }, 30000);
});
