import { beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';
const state=vi.hoisted(()=>({docs:new Map<string,any>(),next:0,queue:Promise.resolve()}));
vi.mock('@/firebase/admin-init',()=>{
 const snapshot=(path:string,docs=state.docs)=>({exists:docs.has(path),id:path.split('/')[1],data:()=>docs.get(path)});
 const ref=(name:string,id:string)=>({path:`${name}/${id}`,id,get:async()=>snapshot(`${name}/${id}`)});
 const query=(name:string,filters:any[]=[],cap=100)=>({where:(k:string,o:string,v:any)=>query(name,[...filters,[k,v]],cap),limit:(n:number)=>query(name,filters,n),orderBy:()=>query(name,filters,cap),get:async()=>{const docs=[...state.docs.entries()].filter(([p,d])=>p.startsWith(name+'/')&&filters.every(([k,v])=>d[k]===v)).slice(0,cap).map(([p])=>snapshot(p));return {docs,size:docs.length,empty:!docs.length,forEach:(f:any)=>docs.forEach(f)}}});
 return {adminAuth:{verifyIdToken:async()=>({uid:'buyer',email:'buyer@example.com',name:'Buyer'})},adminDb:{collection(name:string){return {...query(name),doc:(id?:string)=>ref(name,id||`auto${++state.next}`)}},async runTransaction(fn:any){let release!:()=>void;const old=state.queue;state.queue=new Promise(r=>release=r);await old;const staged=new Map(state.docs);let wrote=false;try{const result=await fn({get:async(r:any)=>{if(wrote)throw Error('Read after write');return r.path?snapshot(r.path,staged):r.get()},set:(r:any,d:any,o:any)=>{wrote=true;staged.set(r.path,o?.merge?{...staged.get(r.path),...d}:d)},update:(r:any,d:any)=>{wrote=true;staged.set(r.path,{...staged.get(r.path),...d})},create:(r:any,d:any)=>{wrote=true;if(staged.has(r.path))throw Error('Already exists');staged.set(r.path,d)}});state.docs=staged;return result;}finally{release()}}}};
});
vi.mock('firebase-admin/firestore',()=>({FieldValue:{serverTimestamp:()=>new Date().toISOString(),arrayUnion:(...v:any[])=>v}}));
import { POST } from '@/app/api/store/purchase/route';
const buy=(body:any={})=>POST(new NextRequest('http://localhost/api/store/purchase',{method:'POST',headers:{Authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify({productId:'Mock',productType:'mock',purchaseRequestId:'request_1234',...body})}));
beforeEach(()=>{state.next=0;state.queue=Promise.resolve();state.docs=new Map([['configs/store',{mockTestPackages:[{name:'Mock',price:100,gstRate:0,months:6}],referboltSubscription:{name:'ReferBolt',price:100,gstRate:0},ibaCommissionRate:10,freeIbaCommissionRate:5}],['users/buyer',{referredBy:'referrer',status:'Active'}],['users/referrer',{status:'Active',purchasedMockTest:true}],['wallets/buyer',{balance:1000,coins:0,referralCode:'REFBUYER'}],['wallets/referrer',{balance:20,coins:0,referralCode:'REFABC'}]]);});
describe('paid subscription referral reward',()=>{
 it('credits ₹5 each once and preserves separate IBA commission',async()=>{const r=await buy();expect(r.status).toBe(200);expect(state.docs.get('wallets/buyer').balance).toBe(905);expect(state.docs.get('wallets/referrer').balance).toBe(35);expect(state.docs.get('referralRewardClaims/buyer')).toMatchObject({amountEach:5,status:'CREDITED'});expect((await buy()).status).toBe(500);expect(state.docs.get('wallets/referrer').balance).toBe(35);});
 it('allows only one of concurrent retries to credit',async()=>{const rs=await Promise.all([buy(),buy()]);expect(rs.filter(r=>r.status===200)).toHaveLength(1);expect(state.docs.get('wallets/buyer').balance).toBe(905);});
 it('does not credit on renewal, free subscription or insufficient funds',async()=>{state.docs.get('users/buyer').purchasedMockTest=true;expect((await buy()).status).toBe(200);expect(state.docs.has('referralRewardClaims/buyer')).toBe(false);state.docs.get('users/buyer').purchasedMockTest=false;state.docs.get('configs/store').mockTestPackages[0].price=0;await buy({purchaseRequestId:'request_free'});expect(state.docs.has('referralRewardClaims/buyer')).toBe(false);state.docs.get('configs/store').mockTestPackages[0].price=100;state.docs.get('wallets/buyer').balance=0;expect((await buy({purchaseRequestId:'request_low'})).status).toBe(500);});
 it('does not repay legacy welcome-bonus recipients',async()=>{state.docs.set('transactions/legacy',{user:'buyer',type:'Welcome Bonus',amount:5});await buy();expect(state.docs.has('referralRewardClaims/buyer')).toBe(false);});
 it('advances premium ReferBolt only on the qualifying subscription',async()=>{state.docs.set('referbolt/referrer',{isSubscribed:true,cycleProgress:2,cycleGoal:3,cyclesCompleted:0,totalReferrals:2,totalCommissions:0,autoRenew:false});expect((await buy()).status).toBe(200);expect(state.docs.get('referbolt/referrer').cyclesCompleted).toBe(1);expect(state.docs.get('wallets/referrer').balance).toBe(40);});
 it('does not overdraw a premium renewal wallet',async()=>{state.docs.set('referbolt/referrer',{isSubscribed:true,cycleProgress:2,cycleGoal:3,cyclesCompleted:3,totalReferrals:11,totalCommissions:0,autoRenew:false});expect((await buy()).status).toBe(200);expect(state.docs.get('wallets/referrer').balance).toBe(35);expect(state.docs.get('referbolt/referrer').isSubscribed).toBe(false);});
 it('rejects invalid, self and duplicate IBA codes before writes',async()=>{expect((await buy({referralCode:'invalid'})).status).toBe(500);expect((await buy({referralCode:'refbuyer'})).status).toBe(500);expect((await buy({referralCode:'refabc',referralCode2:'REFABC'})).status).toBe(400);expect(state.docs.get('wallets/buyer').balance).toBe(1000);});
});
