"use client";
import { useEffect, useState } from 'react';
import { useAuth } from '@/firebase';
import { defaultPageInstructions, type PageInstructions } from '@/lib/page-instructions';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
export default function InstructionsSettings() {
 const { user } = useAuth(); const { toast } = useToast();
 const [data, setData] = useState<PageInstructions>(defaultPageInstructions); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [failed, setFailed] = useState(false);
 useEffect(() => { let active = true; fetch('/api/page-instructions').then(r => { if (!r.ok) throw Error(); return r.json(); }).then(v => { if (active) setData(v); }).catch(() => { if (active) setFailed(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
 function change(kind: keyof PageInstructions, field: string, value: string) { setData(prev => ({ ...prev, [kind]: { ...prev[kind], [field]: value } })); }
 async function upload(kind: keyof PageInstructions, file?: File) { if (!file) return; if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 280000) { toast({ variant: 'destructive', title: 'Choose PNG, JPEG or WebP under 280 KB.' }); return; } const reader = new FileReader(); reader.onload = () => change(kind, 'imageUrl', String(reader.result)); reader.readAsDataURL(file); }
 async function save() { if (!user) return; setSaving(true); try { const token = await user.getIdToken(); const r = await fetch('/api/admin/page-instructions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(data) }); const result = await r.json(); if (!r.ok) throw Error(result.error); toast({ title: 'Instructions saved.' }); } catch (e) { toast({ variant: 'destructive', title: 'Unable to save', description: e instanceof Error ? e.message : 'Try again.' }); } finally { setSaving(false); } }
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Registration & Wallet Instructions</h1><p>These details and images are visible to users. Do not include private information.</p>{loading ? <p>Loading…</p> : <>{failed && <p role="alert">Unable to load settings. Refresh before editing.</p>}{(['registration','wallet'] as const).map(kind => <section key={kind} className="rounded-xl border p-5 space-y-4"><h2 className="text-xl font-semibold">{kind === 'registration' ? 'Student Registration' : 'Fund Wallet'}</h2><Label htmlFor={`${kind}-title`}>Title</Label><Input id={`${kind}-title`} maxLength={150} value={data[kind].title} onChange={e => change(kind,'title',e.target.value)} /><Label htmlFor={`${kind}-details`}>Detailed instructions</Label><Textarea id={`${kind}-details`} rows={8} maxLength={12000} value={data[kind].details} onChange={e => change(kind,'details',e.target.value)} /><Label htmlFor={`${kind}-image`}>Upload image (PNG / JPEG / WebP, under 280 KB)</Label><Input id={`${kind}-image`} type="file" accept="image/png,image/jpeg,image/webp" onChange={e => upload(kind,e.target.files?.[0])} /><Label htmlFor={`${kind}-alt`}>Image description</Label><Input id={`${kind}-alt`} maxLength={250} value={data[kind].imageAlt} onChange={e => change(kind,'imageAlt',e.target.value)} />{data[kind].imageUrl && <><img src={data[kind].imageUrl} alt={data[kind].imageAlt || 'Instruction preview'} className="max-h-72 object-contain" /><Button variant="outline" onClick={() => change(kind,'imageUrl','')}>Remove image</Button></>}</section>)}<Button disabled={saving || failed || !user} onClick={save}>{saving ? 'Saving…' : 'Save Instructions'}</Button></>}</div>;
}
