"use client";

import { useEffect, useState } from "react";
import { Loader2, Mic2, Save } from "lucide-react";
import { useAuth } from "@/firebase";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { defaultStorytellerConfig, StorytellerConfig } from "@/lib/storyteller";

export default function StorytellerAdminPage() {
  const { user } = useAuth(); const { toast } = useToast();
  const [config,setConfig]=useState<StorytellerConfig>(defaultStorytellerConfig); const [busy,setBusy]=useState(true);
  const [analytics,setAnalytics]=useState<any>({});
  useEffect(()=>{ if(user) Promise.all([request("GET"),adminAnalytics()]).then(([d,a])=>{if(d.config)setConfig(d.config);setAnalytics(a.analytics||{})}).finally(()=>setBusy(false)); },[user]);
  async function request(method:string, body?:unknown){ const token=await user!.getIdToken(); const r=await fetch("/api/admin/storyteller/config",{method,headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:body?JSON.stringify(body):undefined}); const d=await r.json(); if(!r.ok)throw new Error(d.error); return d; }
  async function adminAnalytics(){const token=await user!.getIdToken();const r=await fetch("/api/admin/storyteller/analytics",{headers:{authorization:`Bearer ${token}`}});return r.json()}
  async function save(){if(!confirm("Publish these StoryTeller settings? New checkouts will use the new price immediately."))return;setBusy(true);try{await request("PUT",config);toast({title:"StoryTeller settings published"});}catch(e){toast({variant:"destructive",title:"Save failed",description:e instanceof Error?e.message:"Unable to save."});}finally{setBusy(false)}}
  async function uploadDemo(file:File){setBusy(true);try{const token=await user!.getIdToken();const data=new FormData();data.set("file",file);const r=await fetch("/api/admin/storyteller/demo",{method:"POST",headers:{authorization:`Bearer ${token}`},body:data});const d=await r.json();if(!r.ok)throw new Error(d.error);setConfig({...config,demoAssetPath:d.demoAssetPath,demoEnabled:true});toast({title:"Demo Reel uploaded"});}catch(e){toast({variant:"destructive",title:"Upload failed",description:e instanceof Error?e.message:"Upload failed."});}finally{setBusy(false)}}
  const list=(key:keyof StorytellerConfig)=>(config[key] as string[]).join(", ");
  const setList=(key:keyof StorytellerConfig,value:string)=>setConfig({...config,[key]:value.split(",").map(v=>v.trim()).filter(Boolean)});
  const voiceText=config.voices.map(v=>`${v.id}|${v.label}|${v.language}|${v.gender}`).join("\n");
  const setVoices=(value:string)=>setConfig({...config,voices:value.split("\n").map(line=>{const [id,label,language,gender]=line.split("|").map(v=>v.trim());return{id,label,language,gender:gender==="FEMALE"?"FEMALE" as const:"MALE" as const}}).filter(v=>v.id&&v.label&&v.language)});
  const sampleText=config.voiceSamples.map(v=>`${v.label}|${v.language}|${v.assetPath}`).join("\n");
  const setVoiceSamples=(value:string)=>setConfig({...config,voiceSamples:value.split("\n").map(line=>{const [label,language,assetPath]=line.split("|").map(v=>v.trim());return{label,language,assetPath}}).filter(v=>v.label&&v.language&&v.assetPath)});
  const musicText=Object.entries(config.musicAssets||{}).map(([category,path])=>`${category}|${path}`).join("\n");
  const setMusic=(value:string)=>setConfig({...config,musicAssets:Object.fromEntries(value.split("\n").map(line=>line.split("|").map(v=>v.trim())).filter(parts=>parts.length===2&&parts[0]&&parts[1]))});
  if(busy)return <div className="p-10"><Loader2 className="animate-spin"/></div>;
  return <div className="p-4 md:p-8 space-y-6"><div><h1 className="text-3xl font-black flex gap-2"><Mic2/>StoryTeller AI</h1><p className="text-muted-foreground">Admin-controlled pricing, demo and generation policy. No free user generation.</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Demo views",analytics.demoViews],["Purchases",analytics.successfulPurchases],["Completed",analytics.paidReelsGenerated],["Refunds",analytics.refunds],["Revenue",`₹${Number(analytics.totalRevenue||0).toFixed(2)}`],["Avg. price",`₹${Number(analytics.averageSellingPrice||0).toFixed(2)}`],["Failures",analytics.failedGenerations],["Est. margin",`₹${Number(analytics.estimatedGrossMargin||0).toFixed(2)}`]].map(([k,v])=><Card key={String(k)}><CardContent className="pt-5"><p className="text-xs text-muted-foreground uppercase font-bold">{k}</p><p className="text-2xl font-black">{v||0}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>General & Pricing</CardTitle></CardHeader><CardContent className="grid md:grid-cols-2 gap-4"><Toggle label="StoryTeller enabled" value={config.enabled} set={v=>setConfig({...config,enabled:v})}/><Field label="Price per Reel (INR)"><Input type="number" min="1" value={config.reelPrice} onChange={e=>setConfig({...config,reelPrice:Number(e.target.value)})}/></Field><Field label="Product name"><Input value={config.productName} onChange={e=>setConfig({...config,productName:e.target.value})}/></Field><Field label="Tagline"><Input value={config.tagline} onChange={e=>setConfig({...config,tagline:e.target.value})}/></Field><Field label="Description"><Textarea value={config.description} onChange={e=>setConfig({...config,description:e.target.value})}/></Field><Field label="Automatic retries (0–3)"><Input type="number" min="0" max="3" value={config.automaticRetryCount} onChange={e=>setConfig({...config,automaticRetryCount:Number(e.target.value)})}/></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Fixed Demo Reel</CardTitle><CardDescription>Upload or replace the managed MP4 without redeployment.</CardDescription></CardHeader><CardContent className="grid md:grid-cols-2 gap-4"><Toggle label="Demo enabled" value={config.demoEnabled} set={v=>setConfig({...config,demoEnabled:v})}/><Field label="Upload/replace demo MP4 (max 100 MB)"><Input type="file" accept="video/mp4" onChange={e=>e.target.files?.[0]&&uploadDemo(e.target.files[0])}/></Field><Field label="Managed asset path"><Input value={config.demoAssetPath} readOnly/></Field><Field label="Thumbnail URL"><Input value={config.demoThumbnail} onChange={e=>setConfig({...config,demoThumbnail:e.target.value})}/></Field><Field label="Demo title"><Input value={config.demoTitle} onChange={e=>setConfig({...config,demoTitle:e.target.value})}/></Field><Field label="Demo description"><Textarea value={config.demoDescription} onChange={e=>setConfig({...config,demoDescription:e.target.value})}/></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Generation Options</CardTitle></CardHeader><CardContent className="grid md:grid-cols-2 gap-4"><Toggle label="Voice provider enabled" value={config.voiceProviderEnabled} set={v=>setConfig({...config,voiceProviderEnabled:v})}/><Field label="Voice provider"><Input value={config.voiceProvider} onChange={e=>setConfig({...config,voiceProvider:e.target.value})}/></Field><Field label="Voice model"><Input value={config.voiceModel} onChange={e=>setConfig({...config,voiceModel:e.target.value})}/></Field><Field label="Languages (comma separated)"><Input value={list("languages")} onChange={e=>setList("languages",e.target.value)}/></Field><Field label="Durations in seconds"><Input value={config.durations.join(", ")} onChange={e=>setConfig({...config,durations:e.target.value.split(",").map(Number).filter(Number.isFinite)})}/></Field><Field label="Voice styles"><Input value={list("voiceStyles")} onChange={e=>setList("voiceStyles",e.target.value)}/></Field><Field label="Templates"><Input value={list("templates")} onChange={e=>setList("templates",e.target.value)}/></Field><Field label="Music categories"><Input value={list("musicCategories")} onChange={e=>setList("musicCategories",e.target.value)}/></Field><Field label="Voices: id|label|language|MALE/FEMALE"><Textarea rows={5} value={voiceText} onChange={e=>setVoices(e.target.value)}/></Field><Field label="Voice samples: label|language|public asset path"><Textarea rows={5} value={sampleText} onChange={e=>setVoiceSamples(e.target.value)}/></Field><Field label="Music assets: category|Storage path"><Textarea rows={5} value={musicText} onChange={e=>setMusic(e.target.value)}/></Field></CardContent></Card>
    <Button size="lg" onClick={save} disabled={busy}><Save/> Save & Publish</Button>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <div className="flex items-center justify-between border rounded-lg p-3"><Label>{label}</Label><Switch checked={value} onCheckedChange={set}/></div>}
